# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import penguins_pb2 as penguins__pb2


class PenguinsPredictorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictPenguinsSpecies = channel.unary_unary(
                '/penguins.PenguinsPredictor/PredictPenguinsSpecies',
                request_serializer=penguins__pb2.PenguinsPredictRequest.SerializeToString,
                response_deserializer=penguins__pb2.PenguinsPredictReply.FromString,
                )


class PenguinsPredictorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictPenguinsSpecies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PenguinsPredictorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictPenguinsSpecies': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictPenguinsSpecies,
                    request_deserializer=penguins__pb2.PenguinsPredictRequest.FromString,
                    response_serializer=penguins__pb2.PenguinsPredictReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'penguins.PenguinsPredictor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PenguinsPredictor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictPenguinsSpecies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/penguins.PenguinsPredictor/PredictPenguinsSpecies',
            penguins__pb2.PenguinsPredictRequest.SerializeToString,
            penguins__pb2.PenguinsPredictReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
