# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: penguins.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epenguins.proto\x12\x08penguins\"\x94\x01\n\x16PenguinsPredictRequest\x12\x0e\n\x06island\x18\x01 \x01(\t\x12\x16\n\x0e\x62ill_length_mm\x18\x02 \x01(\x01\x12\x15\n\rbill_depth_mm\x18\x03 \x01(\x01\x12\x19\n\x11\x66lipper_length_mm\x18\x04 \x01(\x05\x12\x13\n\x0b\x62ody_mass_g\x18\x05 \x01(\x05\x12\x0b\n\x03sex\x18\x06 \x01(\t\"\'\n\x14PenguinsPredictReply\x12\x0f\n\x07species\x18\x01 \x01(\t2q\n\x11PenguinsPredictor\x12\\\n\x16PredictPenguinsSpecies\x12 .penguins.PenguinsPredictRequest\x1a\x1e.penguins.PenguinsPredictReply\"\x00\x42,\n\x13io.grpc.examples.mlB\rPenguinsProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'penguins_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023io.grpc.examples.mlB\rPenguinsProtoP\001\242\002\003HLW'
  _globals['_PENGUINSPREDICTREQUEST']._serialized_start=29
  _globals['_PENGUINSPREDICTREQUEST']._serialized_end=177
  _globals['_PENGUINSPREDICTREPLY']._serialized_start=179
  _globals['_PENGUINSPREDICTREPLY']._serialized_end=218
  _globals['_PENGUINSPREDICTOR']._serialized_start=220
  _globals['_PENGUINSPREDICTOR']._serialized_end=333
# @@protoc_insertion_point(module_scope)
